context:
  version: "2.0.1"

package:
  name: libmgui
  version: ${{ version }}

source:
  url: https://forge.hekkelman.net/maarten/libmgui/archive/v${{ version }}.tar.gz
  sha256: 908a4c0a32d1b1452e338ef32085019624f67be766aed42deb9d9d7877bfda7d

build:
  number: 0
  skip:
    # Remove windows in the future when we have windows support
    - osx
    - win
  script:
    - if: linux
      then: |
        set -exo pipefail
        cmake -S . -B build ${CMAKE_ARGS} -DBUILD_SHARED_LIBS=ON
        cmake --build build --parallel ${CPU_COUNT}
        cmake --install build

requirements:
  build:
    - ${{ compiler("cxx") }}
    - ${{ stdlib("c") }}
    - ${{ "make" if linux }}
    - cmake
    - pkg-config
  host:
    - expat
    - freetype
    - glib
    - libgxrio
    - Liblzma-devel
    - maartens_resource_compiler
    - zeem
    - if: linux
      then:
        - gtk4
        - libcanberra
    - zlib
  run_exports:
    - ${{ pin_subpackage("libmgui", upper_bound="x.x") }}

tests:
  - package_contents:
      include:
        - mgui/MLib.hpp
      lib:
        - mgui

about:
  homepage: https://forge.hekkelman.net/maarten/libmgui
  repository: https://forge.hekkelman.net/maarten/libmgui
  license: BSD-2-Clause
  license_file: LICENSE
  summary: "Class library for creating gui applications"
  description: |
    This library provides a cross platform application framework.

    The library uses a strict division between client code that is OS agnostic and implementation code using bridge patterns.

extra:
  recipe-maintainers:
    - eunos-1128
